---
# Per environment values which override defaults in hmpps-dpr-tools-ui/values.yaml

generic-service:
  ingress:
    host: dpr-tools-ui.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://dpr-tools-ui.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    API_URL: "http://hmpps-dpr-tools-api-prod.hmpps-dpr-tools-prod.svc.cluster.local"
    TOKEN_VERIFICATION_ENABLED: true

generic-prometheus-alerts:
  alertSeverity: digital-prison-reporting-prod
